### ISSUE TITLE
You might not need jQuery

### ISSUE THREAD

**Issue by julkue** [meta-systems/seometahelper#1]
I've just seen that you are embedding jQuery for jmHighlight v5.2.2.
jmHighlight was renamed to mark.js and jQuery is not necessary anymore, even though it can still be used as jQuery plugin. So head over to the [website](https://markjs.io/) and update your version, then you don't need to include jQuery and speed up the extension.

**Comment by petrovnn** [comment]
Thank you for your note!

I discard the jQuery and move on to a new version of your plug-in as soon as the time will be!

Now my extension is quite slow

**Comment by morovinger** [comment]
now jQuery  absolete https://github.com/meta-systems/seometahelper/commit/d3021a5cac241221e6d71ceb5b493e346b1ee8b0
